apiVersion: v1
kind: Service
metadata:
  name: trading-backend
  labels:
    app: trading-backend
spec:
  type: ClusterIP
  selector:
    app: trading-backend
  ports:
    - port: 3075
      targetPort: 3075
      protocol: TCP
